name: Specification Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-validate:
    name: Lint and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check Markdown and JSON formatting with Prettier
        run: |
          npx --yes prettier@3.3.2 --check "**/*.json"

      - name: Lint Markdown files
        run: |
          npx --yes markdownlint-cli@0.39.0 "**/*.md"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install jsonschema

      - name: Validate golden examples against schemas
        run: |
          python tools/validate_all.py --verbose
